title: "TalkRush"
description: "Chat with strangers and make new friends in free random chat rooms. Enjoy anonymous text, video, and exciting group chat rooms for safe and fun online chatting."
baseurl: "" 
url: "https://shkumaraman.github.io"

# Language and region
lang: "en"
locale: "en_US"

# Default Open Graph
image: "/assets/chat.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
